#include "knackle.h"
#include <raylib.h>
#include <stdio.h>
#define BOARD_SIZE 3

// TODO: Print the number randomly generated by button phase
// BUG: When the user clicks on a column then removes their cursor from the
// board, the game crashes
int main(void) {
  InitWindow(1000, 1000, "raylib [core] example - basic window");

  bool mouse_state;
  DiceSlot *boards[BOARD_SIZE] = {0};
  InitBoard(boards, BOARD_SIZE);

  while (!WindowShouldClose()) {
    bool is_mouse_on_board = IsMouseOnBoard(boards, BOARD_SIZE);
    //-------------------Pressed-Phase-----------------------------------------------
    if (IsMouseButtonDown(MOUSE_BUTTON_LEFT) && is_mouse_on_board) {
      mouse_state = 1;
    }
    if (IsMouseButtonUp(MOUSE_BUTTON_LEFT) && mouse_state) {
      if (!RollDice(boards, BOARD_SIZE, GetMouseColumn()))
        printf("Could not roll dice. This will be replaced with a animation or "
               "something in the future\n");
      mouse_state = 0;
    }
    //---------------------Draw-Phase-----------------------------------------------
    BeginDrawing();
    ClearBackground(GRAY);
    if (is_mouse_on_board) {
      AltColumnColor(boards, GetMouseColumn(), BOARD_SIZE);
    } else {
      DrawBoards(boards, BOARD_SIZE);
    }
    EndDrawing();
  }

  CloseWindow();

  return 0;
}
